//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artista
    {
        public long Id { get; set; }
        public string NombreArtista { get; set; }
        public string DescripcionArtista { get; set; }
        public long Companiaid { get; set; }
    
        public virtual Compania Compania { get; set; }
    }
}
