//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public long Id { get; set; }
        public string MetodoDePago { get; set; }
        public int Unidades { get; set; }
        public int Descuento { get; set; }
        public long LocalidadEspectaculoid { get; set; }
        public long Espectaculoid { get; set; }
    
        public virtual Espectaculo Espectaculo { get; set; }
        public virtual LocalidadEspectaculo LocalidadEspectaculo { get; set; }
    }
}
