//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeatroEntities : DbContext
    {
        public TeatroEntities()
            : base("name=TeatroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artista> Artista { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Compania> Compania { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Espectaculo> Espectaculo { get; set; }
        public virtual DbSet<LocalidadAsiento> LocalidadAsiento { get; set; }
        public virtual DbSet<LocalidadEspectaculo> LocalidadEspectaculo { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Sector> Sector { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
